# -*- mode: python ; coding: utf-8 -*-
#
# AmigaADFGui.spec -- PyInstaller build spec for the Issue #15 Windows GUI.
# AUTO-GENERATED by tools/build_windows.py (kept in sync; do not hand-edit).
# Hook target: amiga_adf_library_builder.gui.app:run
#
# Security: only Python code + declared datas are frozen. No vault/password/
# secret files are bundled; runtime state lives under the portable app base
# dir (PortablePaths) and is created at runtime, never shipped.

import os
import sys

# --- build parameters (mirrored from tools/build_windows.py) ---------------
# SPECPATH is injected by PyInstaller and equals this spec's OWN directory
# (the repo root). Use it directly as the base for resolving sub-paths so the
# spec is portable across machines / OSes (no baked-in absolute paths).
SPECDIR = SPECPATH
TARGET = "onedir"                 # "onedir" | "onefile"
APP_NAME = "AmigaADFLibraryBuilder"                 # shipped exe base name (no .exe suffix)
SCRIPT = os.path.join(SPECDIR, 'app_launcher.py')   # bootstrap -> gui.app:run
PATHEX = [os.path.join(SPECDIR, p) for p in ['src']]
HIDDEN_IMPORTS = ['amiga_adf_library_builder', 'amiga_adf_library_builder.artwork', 'amiga_adf_library_builder.catalog', 'amiga_adf_library_builder.cli', 'amiga_adf_library_builder.enrich', 'amiga_adf_library_builder.exporter', 'amiga_adf_library_builder.exporter_guard', 'amiga_adf_library_builder.grouper', 'amiga_adf_library_builder.gui', 'amiga_adf_library_builder.gui.app', 'amiga_adf_library_builder.gui.layout', 'amiga_adf_library_builder.gui.main_window', 'amiga_adf_library_builder.gui.providers', 'amiga_adf_library_builder.gui.secrets', 'amiga_adf_library_builder.gui.settings', 'amiga_adf_library_builder.gui.state', 'amiga_adf_library_builder.gui.themes', 'amiga_adf_library_builder.gui.worker', 'amiga_adf_library_builder.hasheous', 'amiga_adf_library_builder.initializer', 'amiga_adf_library_builder.local_media', 'amiga_adf_library_builder.logging_utils', 'amiga_adf_library_builder.manual_approvals', 'amiga_adf_library_builder.metadata', 'amiga_adf_library_builder.models', 'amiga_adf_library_builder.naming', 'amiga_adf_library_builder.nfo_render', 'amiga_adf_library_builder.parser', 'amiga_adf_library_builder.paths', 'amiga_adf_library_builder.pipeline', 'amiga_adf_library_builder.playmatch', 'amiga_adf_library_builder.quarantine', 'amiga_adf_library_builder.rtfm', 'amiga_adf_library_builder.rtfm_docs', 'amiga_adf_library_builder.scanner', 'PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets']
CONSOLE = False                 # False for shipped GUI; True for debug
# ---------------------------------------------------------------------------

block_cipher = None


def _collect_datas():
    # Themes are loaded at runtime from the portable themes_dir, so there are
    # no non-Python resources to freeze today. Add real assets here only.
    return []


a = Analysis(
    [SCRIPT],
    pathex=PATHEX,
    binaries=[],
    datas=_collect_datas(),
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

if TARGET == "onefile":
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME + ".exe",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=CONSOLE,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
    )
    coll = None
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME + ".exe",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        console=CONSOLE,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
