#!/usr/bin/env python3
"""Windows PyInstaller build driver for the Issue #15 PySide6 GUI.

This is the single, reproducible entry point for producing the standalone
Windows artifact. It is deliberately runnable on Linux for inspection
(``--help`` / ``--print-cmd``) without PyInstaller installed, and is executed
for real on GitHub Actions ``windows-latest`` (see
``.github/workflows/build-windows.yml``).

What it does
------------
* Discovers every ``amiga_adf_library_builder`` submodule so the frozen binary
  pulls in lazily-imported core modules (artwork/enrich/rtfm are imported only
  inside functions, so PyInstaller will not see them by static analysis).
* Adds the required PySide6 Qt submodules as hidden imports.
* Renders a deterministic ``AmigaADFGui.spec`` (also committed for audit) and
  invokes PyInstaller against it.
* Supports two targets:
    - ``onedir``  (default, MVP): a portable ``AmigaADFLibraryBuilder/`` folder
                  that extracts-and-runs; shipped as ``amiga-adf-gui-portable``.
    - ``onefile`` (secondary): a single ``amiga-adf-gui.exe``; shipped as
                  ``amiga-adf-gui-onefile``.
* The shipped GUI build uses ``console=False``. Pass ``--console`` to produce a
  debug build that keeps a console window.

Security posture
----------------
The bootstrapped hook is ``amiga_adf_library_builder.gui.app:run``. No vault
files, password files, or secrets are frozen -- PyInstaller only bundles Python
code and the (currently empty) declared data list. All runtime state
(config/secrets/logs/cache) is created under the portable app base dir at
runtime via ``PortablePaths``.

This tool does NOT modify GUI logic or the core library.
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

# --- paths -----------------------------------------------------------------
# tools/build_windows.py -> repo root is the parent of tools/
REPO_ROOT = Path(__file__).resolve().parents[1]
PKG_SRC = REPO_ROOT / "src" / "amiga_adf_library_builder"
SPEC_DEFAULT = REPO_ROOT / "AmigaADFGui.spec"
# Discover canonical version from pyproject.toml
import re as _re
_pyproject_text = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
_APPLICATION_VERSION = _re.search(r'^version\s*=\s*"(.*?)"', _pyproject_text, _re.MULTILINE).group(1)
# GH-119 Gap C: write the build-time frozen version module so the frozen app
# does not depend on repo-root pyproject.toml at runtime.
_FROZEN_VERSION_PATH = PKG_SRC / "_frozen_version.py"
_FROZEN_VERSION_PATH.write_text(
    "# AUTO-GENERATED by tools/build_windows.py — DO NOT EDIT.\n"
    "# This file is shipped inside the frozen PyInstaller bundle and imported\n"
    "# by _version.py when sys.frozen is True. It preserves a single canonical\n"
    "# version source (pyproject.toml) at build time.\n"
    f'__version__ = "{_APPLICATION_VERSION}"\n',
    encoding="utf-8",
)
# GH-119 Gap B: generate Windows VERSIONINFO resource text from canonical
# semver. PyInstaller's EXE(version=...) consumes this file and writes the
# RT_VERSION resource into the shipped .exe.
def _semver_to_tuple(version: str) -> tuple[int, int, int, int]:
    """Map canonical 'X.Y.Z' semver to Windows 4-tuple (X,Y,Z,0)."""
    parts = version.split(".")
    while len(parts) < 3:
        parts.append("0")
    return (int(parts[0]), int(parts[1]), int(parts[2]), 0)

_VERSION_INFO_PATH = REPO_ROOT / "tools" / "_version_info.txt"
_FILEVERS = _semver_to_tuple(_APPLICATION_VERSION)
_PRODVERS = _FILEVERS
_VERSION_INFO_PATH.write_text(
    "# UTF-8\n"
    "#\n"
    "# For more details about fixed file info 'ffi' see:\n"
    "# http://msdn.microsoft.com/en-us/library/ms646997.aspx\n"
    "VSVersionInfo(\n"
    "  ffi=FixedFileInfo(\n"
    f"    filevers={_FILEVERS!r},\n"
    f"    prodvers={_PRODVERS!r},\n"
    "    mask=0x3f,\n"
    "    flags=0x0,\n"
    "    OS=0x40004,\n"
    "    fileType=0x1,\n"
    "    subtype=0x0,\n"
    "    date=(0, 0)\n"
    "  ),\n"
    "  kids=[\n"
    "    StringFileInfo([StringTable('040904B0', [\n"
    "      StringStruct('CompanyName', 'Amiga ADF Library Builder'),\n"
    "      StringStruct('FileDescription', 'Amiga ADF Library Builder GUI'),\n"
    f"      StringStruct('FileVersion', '{_APPLICATION_VERSION}'),\n"
    "      StringStruct('InternalName', 'AmigaADFLibraryBuilder'),\n"
    "      StringStruct('OriginalFilename', 'AmigaADFLibraryBuilder.exe'),\n"
    "      StringStruct('ProductName', 'Amiga ADF Library Builder'),\n"
    f"      StringStruct('ProductVersion', '{_APPLICATION_VERSION}'),\n"
    "    ])]),\n"
    "    VarFileInfo([VarStruct('Translation', [1033, 1200])])\n"
    "  ]\n"
    ")\n",
    encoding="utf-8",
)
# Bootstrap is written to the repo root, NOT under build/ -- PyInstaller's
# --clean wipes build/ at startup, which would delete a launcher placed there
# (and then fail with "script ... not found").
LAUNCHER_REL = Path("app_launcher.py")

# --- constants --------------------------------------------------------------
QT_HIDDEN_IMPORTS = [
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
]

# GH-65: the packaged GUI performs artwork processing through the shared core
# (enrich -> artwork.process_artwork_bytes -> `from PIL import Image`, a lazy
# in-function import that PyInstaller static analysis cannot see). Pillow is
# declared in the `gui` extra (pyproject.toml) so the build environment
# installs it; these hidden imports force the frozen bundle to carry the PIL
# top-level package and its core image submodules. `PIL` (the top-level
# package) is the import the runtime code actually performs; `PIL.Image` is
# included so the image API is reachable even if the package __init__ is
# pruned by analysis.
PILLOW_HIDDEN_IMPORTS = [
    "PIL",
    "PIL.Image",
]

# Bootstrap that invokes the documented hook target. Written to build/ at build
# time (gitignored) so the committed spec stays coherent without committing a
# bootstrap file.
LAUNCHER_SRC = '''# -*- coding: utf-8 -*-
"""Bootstrap for the Issue #15 standalone Windows GUI.

Invokes the documented PyInstaller hook target
``amiga_adf_library_builder.gui.app:run`` and propagates its exit code.
"""
import sys

from amiga_adf_library_builder.gui.app import run

if __name__ == "__main__":
    sys.exit(run())
'''


def discover_hidden_imports(pkg_src: Path) -> list[str]:
    """Enumerate every importable submodule under the package source tree.

    Walks ``src/amiga_adf_library_builder`` and returns dotted module names so
    PyInstaller freezes lazily-imported core modules that static analysis misses.
    """
    if not pkg_src.is_dir():
        raise SystemExit(f"package source not found: {pkg_src}")
    mods: list[str] = []
    for p in sorted(pkg_src.rglob("*.py")):
        if "__pycache__" in p.parts:
            continue
        rel = p.relative_to(pkg_src.parent)  # amiga_adf_library_builder/...
        parts = list(rel.with_suffix("").parts)
        if parts[-1] == "__init__":
            parts = parts[:-1]
        if not parts:
            continue
        mods.append(".".join(parts))
    return sorted(set(mods))


def render_spec(
    *,
    target: str,
    name: str,
    launcher_rel: str,
    pathex_rel: list[str],
    hidden_imports: list[str],
    console: bool,
    application_version: str,
    version_info_path: str = "",
) -> str:
    """Render the deterministic PyInstaller spec referenced by this driver.

    ``launcher_rel`` and ``pathex_rel`` are paths relative to the repo root
    (the directory containing this spec). They are resolved at spec-eval time
    via PyInstaller's injected ``SPECPATH`` so the committed spec is portable
    across machines / OSes (no baked-in absolute paths).
    """
    version_kw = f"\n        version=os.path.join(SPECDIR, {version_info_path!r}),\n    " if version_info_path else ""
    return f'''# -*- mode: python ; coding: utf-8 -*-
#
# AmigaADFGui.spec -- PyInstaller build spec for the Issue #15 Windows GUI.
# AUTO-GENERATED by tools/build_windows.py (kept in sync; do not hand-edit).
# Hook target: amiga_adf_library_builder.gui.app:run
#
# Security: only Python code + declared datas are frozen. No vault/password/
# secret files are bundled; runtime state lives under the portable app base
# dir (PortablePaths) and is created at runtime, never shipped.

import os
import sys

# --- build parameters (mirrored from tools/build_windows.py) ---------------
# SPECPATH is injected by PyInstaller and equals this spec's OWN directory
# (the repo root). Use it directly as the base for resolving sub-paths so the
# spec is portable across machines / OSes (no baked-in absolute paths).
SPECDIR = SPECPATH
TARGET = "{target}"                 # "onedir" | "onefile"
APP_NAME = "{name}"                 # shipped exe base name (no .exe suffix)
APPLICATION_VERSION = "{application_version}"
SCRIPT = os.path.join(SPECDIR, {launcher_rel!r})   # bootstrap -> gui.app:run
PATHEX = [os.path.join(SPECDIR, p) for p in {pathex_rel!r}]
HIDDEN_IMPORTS = {hidden_imports!r}
CONSOLE = {console}                 # False for shipped GUI; True for debug
# ---------------------------------------------------------------------------

block_cipher = None


def _collect_datas():
    # Themes are loaded at runtime from the portable themes_dir, so there are
    # no non-Python resources to freeze today. Add real assets here only.
    return []


a = Analysis(
    [SCRIPT],
    pathex=PATHEX,
    binaries=[],
    datas=_collect_datas(),
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

if TARGET == "onefile":
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME + ".exe",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=CONSOLE,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
{version_kw}    )
    coll = None
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME + ".exe",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        console=CONSOLE,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
{version_kw}    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
'''


def build_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="build_windows.py",
        description="Build the Issue #15 Windows GUI with PyInstaller.",
    )
    p.add_argument(
        "--target",
        choices=["onedir", "onefile"],
        default="onedir",
        help="Build target (default: onedir portable folder).",
    )
    p.add_argument(
        "--console",
        action="store_true",
        help="Keep a console window (debug build). Default is windowed (console=False).",
    )
    p.add_argument(
        "--name",
        default=None,
        help="Override the exe base name (default: AmigaADFLibraryBuilder / amiga-adf-gui).",
    )
    p.add_argument(
        "--spec-out",
        type=Path,
        default=SPEC_DEFAULT,
        help="Where to write the generated spec (default: repo root/AmigaADFGui.spec).",
    )
    p.add_argument(
        "--distpath",
        type=Path,
        default=REPO_ROOT / "dist",
        help="PyInstaller dist path (default: repo root/dist).",
    )
    p.add_argument(
        "--workpath",
        type=Path,
        default=REPO_ROOT / "build",
        help="PyInstaller build (work) path (default: repo root/build).",
    )
    p.add_argument(
        "--clean",
        action="store_true",
        help="Pass --clean to PyInstaller (remove previous build artifacts).",
    )
    p.add_argument(
        "--print-cmd",
        action="store_true",
        help="Write the spec and print the PyInstaller command without building (dry run).",
    )
    return p.parse_args()


def main() -> int:
    args = build_args()

    default_names = {"onedir": "AmigaADFLibraryBuilder", "onefile": "amiga-adf-gui"}
    name = args.name or default_names[args.target]

    launcher_path = REPO_ROOT / LAUNCHER_REL
    launcher_path.parent.mkdir(parents=True, exist_ok=True)
    launcher_path.write_text(LAUNCHER_SRC)

    pathex_rel = ["src"]
    launcher_rel = str(LAUNCHER_REL.as_posix())
    hidden_imports = (
        discover_hidden_imports(PKG_SRC)
        + PILLOW_HIDDEN_IMPORTS
        + QT_HIDDEN_IMPORTS
    )
    spec_text = render_spec(
        target=args.target,
        name=name,
        launcher_rel=launcher_rel,
        pathex_rel=pathex_rel,
        hidden_imports=hidden_imports,
        console=bool(args.console),
        application_version=_APPLICATION_VERSION,
        version_info_path="tools/_version_info.txt",
    )

    spec_path = Path(args.spec_out)
    spec_path.parent.mkdir(parents=True, exist_ok=True)
    spec_path.write_text(spec_text)

    pyi_cmd = [
        "pyinstaller",
        str(spec_path),
        f"--distpath={args.distpath}",
        f"--workpath={args.workpath}",
    ]
    if args.clean:
        pyi_cmd.append("--clean")

    if args.print_cmd:
        print(f"# spec written: {spec_path}")
        print("# launcher:    " + str(launcher_path))
        print("# hiddenimports:")
        for hi in hidden_imports:
            print(f"#   - {hi}")
        print(shlex.join(pyi_cmd))
        return 0

    # Real build (only meaningful on Windows; requires PyInstaller installed).
    try:
        from PyInstaller.__main__ import run as pyi_run
    except ImportError:
        print("ERROR: PyInstaller is not installed in this environment.", file=sys.stderr)
        print("Install it with: pip install pyinstaller", file=sys.stderr)
        return 2

    # PyInstaller.__main__.run() expects argv *after* the program name
    # (i.e. sys.argv[1:]). ``pyi_cmd`` keeps a leading "pyinstaller" token only
    # so ``--print-cmd`` prints the natural command; drop it here so the loader
    # does not try to freeze a file literally named "pyinstaller".
    pyi_run(pyi_cmd[1:])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
